# Generated by Django 2.1.7 on 2019-05-21 03:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(help_text='课程名', max_length=150, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='课程名'),
        ),
    ]
