# Generated by Django 2.1.7 on 2019-04-28 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_comments_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='news',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
