# Generated by Django 2.1.7 on 2019-05-21 03:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='title',
            field=models.CharField(help_text='文档标题', max_length=150, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='文档标题'),
        ),
    ]
